services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: crowdlens
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: localpass
    ports: ["5432:5432"]
  backend:
    build: ./backend
    environment:
      POSTGRES_URL: postgres://pgadmin:localpass@db:5432/crowdlens?sslmode=disable
    depends_on: [db]
    ports: ["8080:8080"]
