name: build-and-deploy-ingestion

on:
  push:
    branches: [ master ]
    paths:
      - ingestion/**
      - .github/workflows/ci-cd-ingestion.yml
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_CONTAINER_REGISTRY: acrcrowdlensdev24492.azurecr.io 
  RESOURCE_GROUP: rg-crowdlens-dev
  CONTAINERAPPS_ENVIRONMENT: cae-crowdlens-dev
  APP_NAME: ingestion
  IMAGE_NAME: ingestion
  DOCKERFILE_PATH: ingestion/Dockerfile

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push, then deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          registryUrl: ${{ env.AZURE_CONTAINER_REGISTRY }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.APP_NAME }}
          containerAppEnvironment: ${{ env.CONTAINERAPPS_ENVIRONMENT }}
          dockerfilePath: ${{ env.DOCKERFILE_PATH }}
          imageToBuild: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          environmentVariables: |
            PLACE_ID=demo-place
